name: Pull Request Validation

on:
  pull_request:

jobs:
  pr-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Environment
        run: |
          echo "Installing dependencies"
          sudo apt install build-essentials

      - name: Compile
        run: make compile

      - name: Run Unit Tests
        run: make test
